FROM saundr00/spark:v1

RUN pip install jupyter
RUN echo "export PYSPARK_DRIVER_PYTHON=jupyter" >> ~/.bashrc
RUN echo "export PYSPARK_DRIVER_PYTHON_OPTS='lab --ip 0.0.0.0 --no-browser --allow-root --port 8889'" >> ~/.bashrc

CMD bash
